### ISSUE TITLE
Non consultable 

### ISSUE THREAD

**Issue by Tomansion** [Tchoow/Portfolio#1]
Le lien mis à disposition dans le Readme : [https://github.com/Tchoow/Portfolio/blob/main/mykwad.com](https://github.com/Tchoow/Portfolio/blob/main/mykwad.com)
me redirige vers une page 404

**Comment by Tchoow** [comment]
Merci pour ton issue, le portfolio est à nouveau up à l'adresse suivante : https://tchoow.github.io/Portfolio/
